
# This file was *autogenerated* from the file ../sage/interpolation.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_0p9589 = RealNumber('0.9589'); _sage_const_0p7568 = RealNumber('0.7568'); _sage_const_0p9093 = RealNumber('0.9093'); _sage_const_0p2794 = RealNumber('0.2794'); _sage_const_0p1411 = RealNumber('0.1411'); _sage_const_0p8415 = RealNumber('0.8415')
points = [_sage_const_0 , _sage_const_0p8415 , _sage_const_0p9093 , _sage_const_0p1411 , -_sage_const_0p7568 , -_sage_const_0p9589 , -_sage_const_0p2794 ]

list_plot(points)











